<?php

namespace App\Models;

use CodeIgniter\Model;

class PindustExpedienteModel extends Model
{
  protected $table            = 'pindust_expediente';
  protected $primaryKey       = 'id';
  protected $useAutoIncrement = false;
  protected $returnType       = 'array';
  protected $useSoftDeletes   = false;
  protected $allowedFields    = [
  'idExp', 'tipo_solicitante', 'empresa', 'nif', 'domicilio',
  'alcalde_felib', 'responsable_felib', 'cargo_felib', 'tel_cargo_felib',
  'tecnico_felib', 'cargo_tecnico_felib', 'mail_tecnico_felib',
  'tel_tecnico_felib', 'movil_tecnico_felib', 'felib_p', 'cuantia_ayuda',
  'fecha_kick_off', 'fecha_acta_cierre', 'fecha_REC', 'fecha_REC_enmienda',
  'file_certificadoDocumentacion',
  'file_enviardocumentoIdentificacion',
  'file_escritura_empresa',
  'file_logotipoEmpresaIls',
  'file_informeResumenIls',
  'file_informeInventarioIls',
  'file_modeloEjemploIls',
  'file_certificado_verificacion_ISO',
  'file_certificado_itinerario_formativo',
  'file_lineaProduccionBalearesIls',
  'cumpleRequisitos_dec_resp',
  'cumpleRequisitos_participacion_dec_resp',
  'noArticulo_10_dec_resp',
  'epigrafeIAE_dec_resp',
  'registroIndustrialMinero_dec_resp',
  'aceptaCondicionesConv_dec_resp',
  'declaracion_responsable_consultor',
  'declaracion_responsable_xii',
  'declaracion_responsable_xiii',
  'declaracion_responsable_xiv',
  'declaracion_responsable_xv',
  'declaracion_responsable_xvi',
  'declaro_idi_isba_que_cumple_1',
  'declaro_idi_isba_que_cumple_2',
  'declaro_idi_isba_que_cumple_3',
  'declaro_idi_isba_que_cumple_4',
  'declaro_idi_isba_que_cumple_5',
  'declaro_idi_isba_que_cumple_6',
  'declaro_idi_isba_que_cumple_7',
  'declaro_idi_isba_que_cumple_8',
  'declaro_idi_isba_que_cumple_0',
  'declaro_idi_isba_que_cumple_10',
  'declaro_idi_isba_que_cumple_12',
  'declaro_idi_isba_que_cumple_13',
  'declaro_idi_isba_que_cumple_14',
  'declaro_idi_isba_que_cumple_15',
  'corrientePagoATIB_dec_resp',
  'noConsultarAtib_dec_resp',
  'corrientePagoAEAT_dec_resp',
  'noConsultarAEATSegSoc_dec_resp',
  'ayudasSubven_dec_resp',
  'ayudasSubvenSICuales_dec_resp',
  'cumpleNormativaSegInd_dec_resp',
  'cumpleNormativaMinimos_dec_resp_1',
  'importe_minimis',
  'veracidad_datos_bancarios_1',
  'nom_entidad',
  'domicilio_sucursal',
  'codigo_BIC_SWIFT',
  'cc_datos_bancarios',
  'pais_datos_bancarios',
  'opcion_banco',
  'veracidad_datos_bancarios_2',
  'veracidad_datos_bancarios_3',
  'consentimientoAIDI_dec_resp',
  'consentimiento_identificacion',
  'noHaRecibidoAyudas_dec_resp',
  'noHaRecibidoAyudas_otra_admin',
  'fecha_solicitud',
  'situacion',
  'selloDeTiempo',
  'PublicAccessId',
  'publicAccessIdjustificado',
  'hay_PlanTransforDigital',
  'hay_FacturasHabilitador',
  'hay_JustificantesPagoAHabilitador',
  'convocatoria',
  'doc_informe_favorable_sin_requerimiento',
  'doc_informe_favorable_sin_requerimiento_ils',
  'doc_informe_favorable_con_requerimiento',
  'doc_informe_favorable_con_requerimiento_ils',
  'doc_informe_desfavorable_sin_requerimiento',
  'doc_informe_desfavorable_con_requerimiento',
  'doc_informe_desfavorable_con_requerimiento_ils',
  'doc_prop_res_conces_con_req',
  'doc_prop_res_conces_sin_req',
  'doc_prop_res_denegacion_con_req',
  'doc_prop_res_denegacion_sin_req',
  'doc_prop_res_revocacion_por_no_justificar',
  'doc_res_conces_con_req',
  'doc_res_concesion_adhesion_con_req_ils',
  'doc_res_concesion_adhesion_con_req_auto_ils',
  'doc_res_conces_sin_req',
  'doc_res_concesion_adhesion_sin_req_ils',
  'doc_res_concesion_adhesion_sin_req_auto_ils',
  'doc_res_denegacion_con_req',
  'doc_res_denegacion_con_req_ils',
  'doc_res_denegacion_sin_req',
  'doc_res_pago_con_req',
  'doc_res_pago_sin_req',
  'doc_requeriment',
  'doc_requeriment_ils',
  'doc_requeriment_auto_ils',
  'doc_res_desestimiento_por_renuncia',
  'doc_res_desestimiento_por_no_enmendar',
  'doc_res_desestimiento_por_no_enmendar_ils',
  'doc_renovacion_informe_favorable_ils',
  'doc_renovacion_informe_favorable_con_req_ils',
  'doc_renovacion_informe_desfavorable_ils',
  'doc_renovacion_resolucion_renovacion_marca_ils',
  'doc_renovacion_resolucion_renovacion_marca_con_req_ils',
  'doc_renovacion_resolucion_revocacion_ils',
  'doc_acta_kickoff',
  'doc_acuerdo_amp_term_act_sub',
  'doc_acuerdo_confidencialidad',
  'doc_acta_de_cierre',
  'doc_informe_de_liquidacion',
  'doc_inicio_requerimiento_subsanacion',
  'doc_requerimiento_subsanacion',
  'doc_informe_sobre_la_subsanacion',
  'doc_resolucion_concesion_con_req_20b',
  'doc_prop_res_provisional_favorable_con_req',
  'doc_prop_res_provisional_favorable_sin_req',
  'doc_prop_res_definitiva_con_req',
  'doc_prop_res_definitiva_sin_req',
  'doc_requeriment_adr_isba',
  'doc_prop_res_provisional_adr_isba',
  'doc_prop_res_definitiva_adr_isba',
  'doc_res_concesion_adr_isba',
  'doc_prop_res_provisional_con_requerimiento_adr_isba',
  'doc_prop_res_definitiva_con_requerimiento_adr_isba',
  'doc_res_concesion_con_requerimiento_adr_isba',
  'doc_res_desestimiento_por_no_enmendar_adr_isba',
  'doc_informe_favorable_sin_requerimiento_adr_isba',
  'doc_informe_favorable_con_requerimiento_adr_isba',
  'doc_inicio_requerimiento_justificacion_adr_isba',
  'doc_res_pago_y_justificacion_adr_isba',
  'importeAyuda',
  'porcentajeConcedido',
  'motivoDenegacion',
  'motivoDenegacionIls',
  'motivoRequerimiento',
  'motivoRequerimientoIls',
  'motivoInicioRequerimiento',
  'motivoRequerimientoSubsanacion',
  'motivoRequerimientoJustificacion',
  'motivoSobreSubsanacion',
  'motivogeneraInformeDesfConReq',
  'motivogeneraInformeDesfConReqIls',
  'motivoResolucionRevocacionPorNoJustificar',
  'propuestaTecnicoSobreSubsanacion',
  'actaNumKickOff',
  'actaNumCierre',
  'horaInicioSesionKickOff',
  'horaInicioActaCierre',
  'horaFinSesionKickOff',
  'horaFinActaCierre',
  'lugarSesionKickoff',
  'lugarActaCierre',
  'asistentesKickOff',
  'asistentesActaCierre',
  'tutorKickOff',
  'plazoRealizacionPlan',
  'fecha_HastaRealizacionPlan',
  'observacionesKickOff',
  'observacionesActaCierre',
  'tecnicoAsignado',
  'ordenDePago',
  'fechaEnvioAdministracion',
  'motivoDesestimientoRenuncia',
  'canales_comercializacion_empresa',
  'sitio_web_empresa',
  'video_empresa',
  'fecha_creacion_empresa',
  'publicar_en_web',
  'importe_prestamo',
  'plazo_prestamo',
  'carencia_prestamo',
  'forma_acred_represent_idi_isba1',
  'forma_acred_represent_idi_isba2',
  'forma_acred_represent_idi_isba3',
  'cuantia_aval_idi_isba',
  'plazo_aval_idi_isba',
  'carencia_idi_isba',
  'fecha_aval_idi_isba',
  'finalidad_inversion_idi_isba',
  'empresa_eco_idi_isba',
  'importe_presupuesto_idi_isba',
  'importe_ayuda_solicita_idi_isba',
  'intereses_ayuda_solicita_idi_isba',
  'coste_aval_solicita_idi_isba',
  'gastos_aval_solicita_idi_isba',
  'tiene_ayudas_subv',
  'ayuda_subv_de',
  'ayuda_subv_dg_pol_ind',
  'ayuda_subv_otros',
  'ayuda_subv_otros_detalle',
  'file_escrituraConstitucion',
  'file_certificadoSGR',
  'file_contratoOperFinanc',
  'file_avalOperFinanc',
  'file_certificadoInverECO',
  'file_document_veracidad_datos_bancarios',
  'file_certificadoLey382003',
  'wp_userID', 'comments'];

    protected $useTimestamps = false;

    // Opcionalmente puedes definir validaciones
    protected $validationRules = [
        'idExp'           => 'required|is_natural',
        'tipo_solicitante'=> 'required|max_length[50]',
        'empresa'         => 'required|max_length[255]',
        'nif'             => 'required|alpha_numeric|max_length[10]',
        'domicilio'       => 'required|max_length[255]',
        'telefono'        => 'permit_empty|regex_match[/^[0-9\s\+\-]{7,17}$/]',
        'email'           => 'permit_empty|valid_email|max_length[150]',
        'telefono_rep'    => 'required|regex_match[/^[0-9]{9}$/]',
        'email_rep'       => 'required|valid_email|max_length[150]',
        'cuantia_ayuda'   => 'required|in_list[40 horas,60 horas,80 horas]',
        'fecha_kick_off'  => 'required|valid_date',
        'fecha_acta_cierre' => 'required|valid_date',
        'ref_REC'         => 'required|alpha_numeric|max_length[24]',
        'cpostal'         => 'required|regex_match[/^[0-9]{5}$/]',
        'localidad'       => 'required|max_length[255]',
        'wp_userID'       => 'required|is_natural',
        'comments'        => 'required|string'
    ];

    protected $validationMessages = [
        'nif' => [
            'required' => 'El NIF es obligatorio.',
            'alpha_numeric' => 'El NIF solo puede contener letras y números.'
        ],
        'telefono_rep' => [
            'required' => 'El teléfono del representante es obligatorio.',
            'regex_match' => 'Debe tener exactamente 9 dígitos.'
        ],
    ];
    protected $skipValidation     = false;
}
